spring:
  cloud:
    discovery:
      enabled: true
    config:
      enabled: false
    gateway:
      mvc:
        routes:
          - id: r1
            uri: http://localhost:8120/
            predicates:
              - Path=/customers/**
          - id: r2
            uri: http://localhost:8121/
            predicates:
              - Path=/accounts/**
  application:
    name: gateway-service
server:
  port: 8122
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/